apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-v1-development-eks-admin
  namespace: kube-system
---
# Create ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: api-v1-development-eks-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: api-v1-development-eks-admin
    namespace: kube-system
