replicatCount: 1

image:
  repository: ghcr.io/hassanhashmy-devops-k8-test/awesomeapp
  tag: "test"
  pullPolicy: IfNotPresent

service:
  name: awesomeapp-service
  type: ClusterIP
  port: 80
  targetPort: 80

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 85

serviceAccount:
  create: true
  annotations: {}

ingress:
  enabled: false
