#ingresssss
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  rules:
    - host: api-v1-development-eks.hash.com
      http:
        paths:
          - path: /micor1/?(.*)
            pathType: Prefix
            backend:
              service: 
                name: micro1-srv
                port: 
                  number: 3000
          - path: /micro2/?(.*)
            pathType: Prefix
            backend:
              service: 
                name: micro2-srv
                port: 
                  number: 3000
          - path: /micro3/?(.*)
            pathType: Prefix
            backend:
              service: 
                name: micro3-srv
                port: 
                  number: 3000