apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: awesomeapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: awesomeapp
  template:
    metadata:
      labels:
        app: awesomeapp
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck/
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
